### ISSUE TITLE
endless loop in PelIfd->load

### ISSUE THREAD

**Issue by lsolesen** [pel/pel#11]
Ported from [sourceforge](https://sourceforge.net/tracker/?func=detail&aid=2979466&group_id=108380&atid=650322)

```
I get "Fatal error: Allowed memory size of xxx bytes exhausted" while trying to read some images (see attached file) due to an endless loop in PelIfd which repeatedly loads itself (line: 240)
```

[Testcase created](https://github.com/lsolesen/pel/blob/master/test/bug2979466.php)

**Comment by weberhofer** [comment]
Thanks @mondrake for fixing this issue in #110
