### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mondrake** [pel/pel#144]
@weberhofer now that PHP 7.4 is out, would it be possible to make a new point release (0.9.7?) so that users can composer require that?

Thanks

**Comment by weberhofer** [comment]
That's a good Idea. I will do that.

**Comment by weberhofer** [comment]
The version is released.

**Comment by mondrake** [comment]
That's great!

Thank you

**Comment by mondrake** [comment]
@weberhofer can you please update the package in Packagist, too?

**Comment by weberhofer** [comment]
@lsolesen can you add me as maintainer to packagist or add a webhook for automatic updates?
