### ISSUE TITLE
A non-numeric value encountered at /var/www/nextcloud/apps/maps/vendor/lsolesen/pel/src/PelIfd.php#447

### ISSUE THREAD

**Issue by ggeorgg** [pel/pel#156]
I am using nextcloud maps app which is using this library here. 
When uploading some images without Exif information I get the error "A non-numeric value encountered" in php. Is there a way to fix this error here in the library?

Related Github issue in nextcloud maps repo:
https://github.com/nextcloud/maps/issues/245

Can I send you some sample images to debug this?
If yes, please let me know your mail adress.

Thanks and best regards
Georg

**Comment by KeithTurkowski** [comment]
This image causes this error:
![pel-error](https://user-images.githubusercontent.com/1822160/96024826-e55d4b80-0e19-11eb-8b33-82a8704bbe87.jpg)

**Comment by mondrake** [comment]
Thanks @KeithTurkowski the failing image file helps a lot!

I could include the image in a test case and fix the failure in #163.

**Comment by mondrake** [comment]
What's happening with the image here is probably unexpected endianness for the GPS IFD. If you scan the image with exiftool, the GPS information is reported. If you scan it via PHP exif_read_data, it is not, and it is not reported the IFD1/Thumbnail info as well. PEL is probably failing similarly to PHP exiflib.
