### ISSUE TITLE
PEL 0.9.10 does not write JPEG files correctly

### ISSUE THREAD

**Issue by mondrake** [pel/pel#182]
drupal/file_mdm_exif  started failing automated tests as soon as it started installing PEL 0.9.10

https://www.drupal.org/pift-ci-job/1950778

Introducing a conflict to this version in composer.json is sufficient to go back to installing 0.9.9, which works OK.

Apparently the issue is with saving JPEG files.

**Comment by IT-Cru** [comment]
Maybe duplicate or very similar issue like #183 ?

**Comment by weberhofer** [comment]
Please test with latest release 0.9.12
